# Generated by Django 5.2.5 on 2025-08-23 10:33

import django.db.models.deletion
import utilities.global_functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(db_index=True, default=utilities.global_functions.generate_uuid, editable=False, help_text='Unique identifier for external reference', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Status to check if the entity is active')),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(help_text='Enter the title of the post', max_length=255)),
                ('content', models.TextField(help_text='Write the content of the post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='posts_title_b9805f_idx')],
            },
        ),
    ]
